apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-bootcamp
  labels:
    app: kubernetes-bootcamp
spec:
  selector:
    matchLabels:
      app: kubernetes-bootcamp
  replicas: 2
  template:
    metadata:
      labels:
        app: kubernetes-bootcamp
    spec:
      containers:
      - name: kubernetes-bootcamp
        image: 1598415/devopsrepo2021:latest
        ports:
          - containerPort: 3000
      - name: master
        image: redis
        command:
          - redis-server
        ports:
          - containerPort: 6379
