name: Redis Service Example

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image:  node:10.16-jessie

    services:
      redis:
        image: redis
        ports:
        - 3000:3000
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v1

    - run: npm ci
      working-directory: ./lab/lab5/assets/userapi/src

    - run: node dbClient.js
      working-directory: ./lab/lab5/assets/userapi/src
      env:
        REDIS_HOST: redis
        REDIS_PORT: ${{ job.services.redis.ports[3000] }}

  vm-job:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
        - 3000/tcp
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v1

    - run: npm ci
      working-directory: ./lab/lab5/assets/userapi/src

    - run: node dbClient.js
      working-directory: ./lab/lab5/assets/userapi/src
      env:
        REDIS_HOST: localhost
        REDIS_PORT: ${{ job.services.redis.ports[3000] }}
